#!/usr/bin/env bash
#
# Multi-Agent Orchestrator - Automated Setup Script
# Usage: ./setup.sh [--yes] [--mock] [--no-browser] [--port 5050]
#

set -euo pipefail

APP_NAME="Multi-Agent Orchestrator"
DEFAULT_PORT="${PORT:-5050}"
AUTO_YES=false
USE_MOCK=false
OPEN_BROWSER=true

# --- Argument parsing ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    -y|--yes) AUTO_YES=true; shift ;;
    --mock) USE_MOCK=true; shift ;;
    --no-browser) OPEN_BROWSER=false; shift ;;
    --port) DEFAULT_PORT="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: ./setup.sh [OPTIONS]"
      echo "Options:"
      echo "  -y, --yes         Non-interactive mode (use env vars)"
      echo "  --mock            Use mock LLM responses (testing)"
      echo "  --no-browser      Don't open browser after setup"
      echo "  --port PORT       Server port (default: 5050)"
      exit 0 ;;
    *) echo "Unknown argument: $1"; exit 2 ;;
  esac
done

# --- Logging functions ---
log()   { printf "\033[1;34m[INFO]\033[0m %s\n" "$*"; }
ok()    { printf "\033[1;32m✓\033[0m %s\n" "$*"; }
warn()  { printf "\033[1;33m⚠\033[0m %s\n" "$*"; }
err()   { printf "\033[1;31m✗\033[0m %s\n" "$*"; exit 1; }

need_cmd() { command -v "$1" >/dev/null 2>&1; }

echo ""
echo "╔═══════════════════════════════════════════════╗"
echo "║   Multi-Agent Orchestrator Setup (v0.3.0)    ║"
echo "╚═══════════════════════════════════════════════╝"
echo ""

# --- 1) Check/Install Python 3.11+ ---
log "Step 1/7: Checking Python version..."

if need_cmd python3; then
  PY_VERSION=$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
  PY_MAJOR=${PY_VERSION%%.*}
  PY_MINOR=${PY_VERSION#*.}
  PY_MINOR=${PY_MINOR%%.*}

  if (( PY_MAJOR > 3 || (PY_MAJOR == 3 && PY_MINOR >= 11) )); then
    ok "Python $PY_VERSION found"
  else
    err "Python 3.11+ required (found: $PY_VERSION). Install: sudo apt install python3.11"
  fi
else
  err "Python3 not found. Install: sudo apt update && sudo apt install python3.11 python3.11-venv"
fi

# --- 2) Create virtual environment ---
log "Step 2/7: Setting up virtual environment..."

if [[ ! -d .venv ]]; then
  python3 -m venv .venv
  ok "Virtual environment created"
else
  ok "Virtual environment exists"
fi

# Activate venv
source .venv/bin/activate

# --- 3) Install dependencies ---
log "Step 3/7: Installing dependencies..."

if [[ ! -f requirements.txt ]]; then
  err "requirements.txt not found in current directory"
fi

pip install --upgrade pip wheel setuptools -q
pip install -r requirements.txt -q
ok "Dependencies installed"

# --- 4) Configure API keys ---
log "Step 4/7: Configuring API keys..."

if [[ -f .env ]]; then
  ok ".env file exists (skipping interactive setup)"
  source .env || true
else
  if $AUTO_YES; then
    OPENAI_KEY="${OPENAI_API_KEY:-}"
    ANTHROPIC_KEY="${ANTHROPIC_API_KEY:-}"
    GOOGLE_KEY="${GOOGLE_API_KEY:-}"
  else
    echo ""
    echo "API Keys Configuration"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "At least ONE provider key required. Press Enter to skip."
    echo ""
    read -rp "OpenAI API Key (sk-...): " OPENAI_KEY || OPENAI_KEY=""
    read -rp "Anthropic API Key (sk-ant-...): " ANTHROPIC_KEY || ANTHROPIC_KEY=""
    read -rp "Google API Key (optional): " GOOGLE_KEY || GOOGLE_KEY=""
    echo ""
  fi

  # Validate at least one key
  if [[ -z "$OPENAI_KEY" && -z "$ANTHROPIC_KEY" && -z "$GOOGLE_KEY" ]]; then
    if ! $USE_MOCK; then
      warn "No API keys provided. Starting in MOCK mode..."
      USE_MOCK=true
    fi
  fi

  # Create .env file
  cat > .env <<EOF
# Multi-Agent Orchestrator Configuration
# Generated by setup.sh on $(date)

# API Keys
OPENAI_API_KEY=${OPENAI_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
GOOGLE_API_KEY=${GOOGLE_KEY}

# Optional: OpenRouter
OPENROUTER_API_KEY=

# Testing
LLM_MOCK=${USE_MOCK}

# Server
PORT=${DEFAULT_PORT}
EOF

  ok ".env file created"
fi

# --- 5) Initialize database ---
log "Step 5/7: Initializing memory database..."

# Database auto-creates on first run, but we can verify
mkdir -p data/MEMORY data/CONVERSATIONS
ok "Database directories ready"

# --- 6) Run tests ---
log "Step 6/7: Running health checks..."

if pytest tests/ -q --tb=no >/dev/null 2>&1; then
  ok "All tests passed"
else
  warn "Some tests failed (non-critical, continuing...)"
fi

# --- 7) Start server ---
log "Step 7/7: Starting API server..."

# Kill any existing server on the port
if lsof -ti:${DEFAULT_PORT} >/dev/null 2>&1; then
  warn "Port ${DEFAULT_PORT} in use. Killing existing process..."
  kill $(lsof -ti:${DEFAULT_PORT}) 2>/dev/null || true
  sleep 1
fi

# Start server in background
nohup python -m uvicorn api.server:app \
  --host 0.0.0.0 \
  --port "${DEFAULT_PORT}" \
  --log-level info \
  > .server.log 2>&1 &

SERVER_PID=$!
sleep 2

# Health check
HEALTH_URL="http://localhost:${DEFAULT_PORT}/health"
for i in {1..10}; do
  if curl -fsS "$HEALTH_URL" >/dev/null 2>&1; then
    ok "Server is running (PID: $SERVER_PID)"
    break
  fi
  if [[ $i -eq 10 ]]; then
    err "Server failed to start. Check .server.log for details"
  fi
  sleep 1
done

# --- Success! ---
echo ""
echo "╔═══════════════════════════════════════════════╗"
echo "║              Setup Complete! 🎉               ║"
echo "╚═══════════════════════════════════════════════╝"
echo ""
echo "🌐 Web UI:       http://localhost:${DEFAULT_PORT}"
echo "📚 API Docs:     http://localhost:${DEFAULT_PORT}/docs"
echo "❤️  Health:      http://localhost:${DEFAULT_PORT}/health"
echo ""
echo "📋 Quick Commands:"
echo "   make agent-ask AGENT=builder Q='Your question'"
echo "   make memory-search Q='keyword'"
echo "   make memory-stats"
echo ""
echo "📄 Logs:         tail -f .server.log"
echo "🔌 Stop Server:  kill $SERVER_PID"
echo ""

# Open browser
if $OPEN_BROWSER; then
  if need_cmd xdg-open; then
    xdg-open "http://localhost:${DEFAULT_PORT}" 2>/dev/null || true
  elif need_cmd open; then
    open "http://localhost:${DEFAULT_PORT}" 2>/dev/null || true
  fi
fi

# Show provider status
echo "Provider Status:"
curl -fsS "$HEALTH_URL" 2>/dev/null | python3 -c "
import sys, json
data = json.load(sys.stdin)
print(f\"  Available: {', '.join(data.get('available_providers', []))}\")
print(f\"  Total: {data.get('total_available', 0)}\")
" || true

echo ""
echo "Happy orchestrating! 🤖"
echo ""
